import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalContext } from "./global/GlobalContext";
import { ClerkProvider } from "@clerk/nextjs";
import { dbConfig } from "@/utils/dbConfig";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConfig();
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className=" min-h-[98vh] m-2 border rounded-md">
            <GlobalContext>{children}</GlobalContext>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
