import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable";
import SideBar from "./siderbar/SideBar";
import PostContent from "./post/PostContent";
import DisplayPost from "./displayPost/DisplayPost";
import MainPageLayout from "./MainPageLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative h-[98vh] w-full bg-slate-50">
          <ResizablePanelGroup
            direction="horizontal"
            className=" w-full rounded-lg border"
          >
            <ResizablePanel minSize={5} maxSize={20} defaultSize={20}>
              <div className="flex h-full items-center justify-center p-2">
                <span className="h-full font-semibold w-full">
                  <SideBar />
                </span>
              </div>
            </ResizablePanel>

            {/* <MainPageLayout children={children} /> */}

            <ResizableHandle withHandle />
            <ResizablePanel defaultSize={75}>
              <div className="flex h-full items-center w-full justify-center p-2">
                <span className="h-full w-full font-semibold">{children}</span>
              </div>
            </ResizablePanel>
            <ResizableHandle withHandle />
            <ResizablePanel defaultSize={30} minSize={25} maxSize={60}>
              <div className="flex h-full w-full items-center justify-center p-2">
                <span className="w-full h-full font-semibold ">
                  <DisplayPost />
                </span>
              </div>
            </ResizablePanel>
          </ResizablePanelGroup>
        </div>
      </body>
    </html>
  );
}
