import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable";
import SideBar from "./siderbar/SideBar";
import PostContent from "./post/PostContent";
import DisplayPost from "./displayPost/DisplayPost";
import MainPageLayout from "./MainPageLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainPageLayout children={children} />
      </body>
    </html>
  );
}
